### ISSUE TITLE
posting a comment destroys the .sqlite 

### ISSUE THREAD

**Issue by cAstraea** [knpuniversity/symfony-guard-demo#1]
Hello, 
Having a problem , trying this out , posting a comment on an article renders it unusable

CRITICAL - Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.username AS username_2, t0.email AS email_3, t0.password AS password_4, t0.roles AS roles_5 FROM User t0 WHERE t0.id = ?' with params [2]: SQLSTATE[HY000]: General error: 11 database disk image is malformed" at /vagrant/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 
Context: {"exception":"Object(Doctrine\DBAL\Exception\DriverException)"}

---update 
disregard this please I changed to pdo_mysql and it's ok now

**Comment by weaverryan** [comment]
Glad you got it worked out - that was a strange error :)
